const workers = [
  {
    id: 1,
    dni: 4000000,
    name: "ACEVEDO JHONG, DANIEL",
    unit: "UNIDAD 1",
    area: "ÁREA 1",
    position: "PUESTO 1",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Ancash",
    hotel: "hotel-1",
    status: "Aislamiento Unidad Minera",
    campaign: "2020-1",
    picture: "https://randomuser.me/api/portraits/thumb/men/1.jpg",
  },
  {
    id: 2,
    dni: 4000001,
    name: "CARRILLO SEGURA, ESTALINS",
    unit: "UNIDAD 2",
    area: "ÁREA 2",
    position: "PUESTO 2",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-2",
    status: "Aislamiento Casa",
    campaign: "2020-1",
    picture: "https://randomuser.me/api/portraits/thumb/women/1.jpg",
  },
  {
    id: 3,
    dni: 4000002,
    name: "GAMARRA ASTETE, ROBERTO",
    unit: "UNIDAD 3",
    area: "ÁREA 3",
    position: "PUESTO 3",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "San Martin",
    hotel: "hotel-1",
    status: "Aislamiento Hotel",
    campaign: "2020-3",
    picture: "https://randomuser.me/api/portraits/thumb/men/2.jpg",
  },
  {
    id: 4,
    dni: 4000003,
    name: "MEDINA ZUTA, OSCAR ENRIQUE",
    unit: "UNIDAD 4",
    area: "ÁREA 4",
    position: "PUESTO 4",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Ancash",
    hotel: "hotel-3",
    status: "Hospitalización",
    campaign: "2020-1",
    picture: "https://randomuser.me/api/portraits/thumb/men/3.jpg",
  },
  {
    id: 5,
    dni: 4000004,
    name: "TORRES GASPAR, MIGUEL ANGEL",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/men/4.jpg",
  },
  {
    id: 6,
    dni: 4000005,
    name: "GARCÍA PERALTA, MIRIAM",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/women/2.jpg",
  },
  {
    id: 7,
    dni: 4000006,
    name: "THERRERA CARBAJAL, MILAGROS SUSAN",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/women/3.jpg",
  },
  {
    id: 8,
    dni: 4000007,
    name: "LLAJA TAFUR, ROBERTO JULIAN",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/men/5.jpg",
  },
  {
    id: 9,
    dni: 4000008,
    name: "MEDINA ZUTA, OSCAR ENRIQUE",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/men/6.jpg",
  },
  {
    id: 10,
    dni: 4000009,
    name: "ORE REYES, OLGA",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/women/4.jpg",
  },
  {
    id: 11,
    dni: 4000010,
    name: "PASTOR PORRAS, ARTURO",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/men/7.jpg",
  },
  {
    id: 12,
    dni: 4000011,
    name: "RIOS LIMA, TERESA",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/women/5.jpg",
  },
  {
    id: 13,
    dni: 40000012,
    name: "SALCEDO DEL PINO, CELIN",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/women/6.jpg",
  },
  {
    id: 14,
    dni: 40000013,
    name: "TRUJILLO PARODI, JACQUELIN",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/women/7.jpg",
  },
  {
    id: 15,
    dni: 4000014,
    name: "VEGA CARREAZO, RUTH NORICILA",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/women/8.jpg",
  },
  {
    id: 16,
    dni: 4000015,
    name: "ZEGARRA SALCEDO, JUAN CARLOS",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/men/8.jpg",
  },
  {
    id: 17,
    dni: 4000016,
    name: "DE LOAYZA CONTERNO, ANTONIO",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/men/9.jpg",
  },
  {
    id: 18,
    dni: 4000017,
    name: "GUZMAN QUISPE, CLARA",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/women/9.jpg",
  },
  {
    id: 19,
    dni: 4000018,
    name: "LLAJA TAFUR, ROBERTO JULIAN",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/men/10.jpg",
  },
  {
    id: 20,
    dni: 4000019,
    name: "HUAPAYA RAYGADA, LUIS ARMANDO",
    unit: "UNIDAD 5",
    area: "ÁREA 5",
    position: "PUESTO 5",
    type: "CONTRATADO",
    vulnerable: "",
    contacts: [],
    activities: [],
    region: "Arequipa",
    hotel: "hotel-4",
    status: "Hospitalización",
    campaign: "2020-2",
    picture: "https://randomuser.me/api/portraits/thumb/men/11.jpg",
  },
];

export default workers;
